# -*- coding: utf-8 -*-
"""RA1 - Contrução de Interpretadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5yK58_bFXHF9YAE_TSFBa98rxYdeOH3
"""

# Melyça Neres e Thaíssa Calil
# RA1 - Parser Lógica Proposicional
# Construção de Interpretadores - BCC - 7C

from ast import parse
import sys
##import re

# dicionario com os tokens especiais
dicionario = {
    r'\neg': 'NEGACAO',
    r'\wedge': 'E',
    r'\vee': 'OU',
    r'\rightarrow': 'IMPLICA',
    r'\leftrightarrow': 'BICONDICIONAL',
    r'true': 'TRUE',
    r'false': 'FALSE',
    r'(': 'ABRE',
    r')': 'FECHA'
}

def analisador_lexico(expressao):  # analisador lexico (simula uma maquina de estados)
    tokens = []
    partes = expressao.strip().split()  # separa a expressao por espacos
    for parte in partes:
        if parte in dicionario:  # verifica se é um token especial conhecido
            tokens.append(dicionario[parte])
        elif ehh_proposicao(parte):
            tokens.append('PROPOSICAO')
        else:  # caso contrário, token inválido
            return None
    return tokens

def ehh_proposicao(parte): #para validadar preposições
  if not parte:
    return False #string vazia ->> inválida
  if not parte[0].isdigit():
    return False
  for c in parte[1:]:  #verificar caracteres após o primeiro [x:]
    if not (c.isdigit() or c.islower()):
      return False
  return True

class Parser:# parser LL(1) por descida recursiva
    def __init__(self, tokens):
        self.tokens = tokens  # lista de tokens recebida
        self.pos = 0  # posicao atual na lista de tokens

    # retorna o token atual
    def token_atual(self):
        if self.pos < len(self.tokens):
            return self.tokens[self.pos]
        return None

    # consome o token se ele for o esperado
    def consumir(self, esperado):
        if self.token_atual() == esperado:
            self.pos += 1
            return True
        return False

    # regra principal da gramatica: formula
    def formula(self):
        tok = self.token_atual()

        # ve se e constante ou proposicao
        if tok == 'TRUE' or tok == 'FALSE' or tok == 'PROPOSICAO':
            self.pos += 1
            return True

        # formula unaria ou binaria
        elif tok == 'ABRE':
            self.pos += 1  # consome '('

            # verifica se e uma formula unaria (negacao)
            if self.token_atual() == 'NEGACAO':
                self.pos += 1
                if self.formula():
                    return self.consumir('FECHA')  # espera ')'
                return False

            # verifica se e uma formula binaria
            elif self.token_atual() in {'E', 'OU', 'IMPLICA', 'BICONDICIONAL'}:
                self.pos += 1
                if self.formula() and self.formula():
                    return self.consumir('FECHA')  # espera ')'
                return False

            return False  # caso nao seja nenhum dos dois
        return False  # token inesperado

    # funcao principal do parser
    def parse(self):
        # a formula e valida se for reconhecida e todos os tokens forem consumidos
        if self.formula() and self.pos == len(self.tokens):
            return True
        return False

def main(): # funcao principal do programa
    if len(sys.argv) < 2:
        print("Uso: python nome_do_arquivo.py testeX.txt")
        return

    nome_arq = sys.argv[1]

    try:
        with open(nome_arq, 'r') as f:
            linhas = f.readlines()
    except FileNotFoundError:
        print("Arquivo não encontrado")
        return

    try:
        qtd = int(linhas[0].strip())
        expressoes = linhas[1:]
    except:
        print("Erro na leitura das expressoes")

    if len(expressoes) != qtd:
        print("Numero de expressoes diferente do informado")
        return

    for expressao in expressoes:
      tokens = analisador_lexico(expressao)
      if tokens is None:
        print("Token inválido")
      else:
        parse= Parser(tokens)
        print("valida" if parse.parse() else "invalida")

if __name__ == "__main__":# executa o programa
    main()